// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojxcpqyxvhptobkkwxma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeGNwcXl4dmhwdG9ia2t3eG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMDc0MDQsImV4cCI6MjA1MzU4MzQwNH0.ahPSfFhUMKW1DakYZoECVFr5dKjtYt5RuOZ0_c5J4iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);